services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/tv:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096